working on build flags

diff --git a/.github/actions/go-build/action.yml b/.github/actions/go-build/action.yml
--- a/.github/actions/go-build/action.yml
+++ b/.github/actions/go-build/action.yml
@@ -3,7 +3,7 @@ description: "Build the go code within the opg-reports repository so it can then
 
 inputs:
   ldflags:
-    description: "Build time ldflags to use in the build commands. Should include the argument"
+    description: "Build time ldflags to use in the build commands. Should include the -ldflags as well."
     default: ""
 
   create_artifact:
@@ -49,7 +49,7 @@ runs:
       env:
         passed: "✅"
         failed: "❌"
-        FLAGS: "${{ inputs.ldflags != '' && '-ldflags=' || '' }}"
+        FLAGS: ${{ inputs.ldflags }}
       run: |
         echo "Build go"
 
@@ -62,21 +62,21 @@ runs:
         go mod tidy
 
         echo -n "[building] collectors/awscosts .......... "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/awscosts ./collectors/awscosts/main.go && echo "${passed}" || echo "${failed}"
+        go build ${{ env.FLAGS }} -o ${build_dir}/awscosts ./collectors/awscosts/main.go && echo "${passed}" || echo "${failed}"
         echo -n "[building] collectors/awsuptime ......... "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/awsuptime ./collectors/awsuptime/main.go && echo "${passed}" || echo "${failed}"
+        go build ${{ env.FLAGS }} -o ${build_dir}/awsuptime ./collectors/awsuptime/main.go && echo "${passed}" || echo "${failed}"
         echo -n "[building] collectors/githubreleases .... "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/githubreleases ./collectors/githubreleases/main.go && echo "${passed}" || echo "${failed}"
+        env CGO_ENABLED=1 go build ${{ env.FLAGS }} -o ${build_dir}/githubreleases ./collectors/githubreleases/main.go && echo "${passed}" || echo "${failed}"
         echo -n "[building] collectors/githubstandards ... "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/githubstandards ./collectors/githubstandards/main.go && echo "${passed}" || echo "${failed}"
+        env CGO_ENABLED=1 go build ${{ env.FLAGS }} -o ${build_dir}/githubstandards ./collectors/githubstandards/main.go && echo "${passed}" || echo "${failed}"
         echo -n "[building] convertor .................... "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/convertor ./convertor/main.go && echo "${passed}" || echo "${failed}"
+        env CGO_ENABLED=1 go build ${{ env.FLAGS }} -o ${build_dir}/convertor ./convertor/main.go && echo "${passed}" || echo "${failed}"
         echo -n "[building] importer ..................... "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/importer ./importer/main.go && echo "${passed}" || echo "${failed}"
+        env CGO_ENABLED=1 go build ${{ env.FLAGS }} -o ${build_dir}/importer ./importer/main.go && echo "${passed}" || echo "${failed}"
         echo -n "[building] servers/api .................. "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/api ./servers/api/main.go && echo "${passed}" || echo "${failed}"
+        env CGO_ENABLED=1 go build ${{ env.FLAGS }} -o ${build_dir}/api ./servers/api/main.go && echo "${passed}" || echo "${failed}"
         echo -n "[building] servers/front ................ "
-        env CGO_ENABLED=1 go build ${{ env.FLAGS }}${{ inputs.ldflags }} -o ${build_dir}/front ./servers/front/main.go && echo "${passed}" || echo "${failed}"
+        env CGO_ENABLED=1 go build ${{ env.FLAGS }} -o ${build_dir}/front ./servers/front/main.go && echo "${passed}" || echo "${failed}"
 
 
         echo "os_arch=${os_arch}" >> $GITHUB_OUTPUT
